-- V1: Create PostgreSQL ENUM types for Bharat Pass
CREATE TYPE application_type AS ENUM ('FRESH', 'RENEWAL', 'REISSUE', 'DIPLOMATIC', 'OFFICIAL');
CREATE TYPE application_category AS ENUM ('NORMAL', 'TATKAAL', 'SUPER_TATKAAL');
CREATE TYPE application_stage AS ENUM (
    'INITIATED', 'EKYC_VERIFIED', 'FORM_SUBMITTED', 'DOCUMENTS_UPLOADED',
    'PAYMENT_COMPLETED', 'APPOINTMENT_BOOKED', 'PSK_APPOINTMENT_COMPLETED',
    'PVS_DISPATCHED', 'POLICE_VERIFIED', 'GRANTED', 'PRINTING_QUEUED',
    'DISPATCHED_SPEED_POST', 'DELIVERED', 'REJECTED', 'ON_HOLD'
);
CREATE TYPE time_window AS ENUM (
    'SLOT_0900', 'SLOT_0930', 'SLOT_1000', 'SLOT_1030',
    'SLOT_1100', 'SLOT_1130', 'SLOT_1200', 'SLOT_1230',
    'SLOT_1300', 'SLOT_1330', 'SLOT_1400', 'SLOT_1430',
    'SLOT_1500', 'SLOT_1530'
);
CREATE TYPE document_type AS ENUM (
    'PHOTO', 'AADHAAR_EKYC', 'PAN_CARD', 'BIRTH_CERTIFICATE',
    'SCHOOL_LEAVING', 'VOTER_ID', 'ELECTRICITY_BILL', 'BANK_STATEMENT',
    'MARRIAGE_CERTIFICATE', 'AFFIDAVIT', 'ANNEXURE_A', 'ANNEXURE_D',
    'ANNEXURE_E', 'ANNEXURE_F', 'ANNEXURE_H', 'ANNEXURE_I', 'NOC_EMPLOYER'
);
CREATE TYPE gender_type AS ENUM ('M', 'F', 'O');
CREATE TYPE appointment_status AS ENUM ('RESERVED', 'BOOKED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED');
CREATE TYPE verification_verdict AS ENUM ('CLEAR', 'ADVERSE', 'INCOMPLETE');
CREATE TYPE user_role AS ENUM ('ROLE_CITIZEN', 'ROLE_PSK_OFFICER', 'ROLE_POLICE_OFFICER', 'ROLE_RPO_ADMIN', 'ROLE_SUPER_ADMIN');
