package com.bharatpass.common.enums;

public enum ApplicationStage {
    INITIATED,
    EKYC_VERIFIED,
    FORM_SUBMITTED,
    DOCUMENTS_UPLOADED,
    PAYMENT_COMPLETED,
    APPOINTMENT_BOOKED,
    PSK_APPOINTMENT_COMPLETED,
    PVS_DISPATCHED,
    POLICE_VERIFIED,
    GRANTED,
    PRINTING_QUEUED,
    DISPATCHED_SPEED_POST,
    DELIVERED,
    REJECTED,
    ON_HOLD
}
